apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp-deployment
  labels:
    app: my-webapp
spec:
  replicas: 3       # Number of replicas (pods) to run for the application
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
        - name: webapp
          image: your_username/your_webapp_image:latest   # Replace with your Docker image repository and tag
          ports:
            - containerPort: 80   # Port your application listens on inside the container

